### ISSUE TITLE
dotNetify-Blazor and partitioned MultiCast VMs

### ISSUE THREAD

**Issue by dompa** [dsuryd/dotNetify-Blazor#3]
Hi,

Do you know if the Blazor version of dotNetify works with partitioned MultiCast VMs?
I've tried for several days now to build a partitioned VM for chatting and everything works fine when I run the project in Visual Studio, but when I publish the project to Azure, the client crashes with this error:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: A member with the name '' already exists on 'System.Action`1[DotNetify.Blazor.ExceptionEventArgs]'. Use the JsonPropertyAttribute to specify another name.
Newtonsoft.Json.JsonSerializationException: A member with the name '' already exists on 'System.Action`1[DotNetify.Blazor.ExceptionEventArgs]'. Use the JsonPropertyAttribute to specify another name.
   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateConstructorParameters(ConstructorInfo constructor, JsonPropertyCollection memberProperties)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at DotNetify.Blazor.JSInteropExtensions.Serialize[VMConnectOptions](VMConnectOptions arg, Boolean camelCase)
   at DotNetify.Blazor.VMContext`1[[SameSocial.Client.Pages.ChatRoom.IGroupChatState, SameSocial.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )

I have tried this using both .net 6 and now also .net 5, but same result.
Using other VMs works great, it's just when I try to have a partitioned one that it fails and I would love to use this functionality, since I have used it many times in React and it's awesome :)

**Comment by dsuryd** [comment]
I'm happy to help! May I see how you wrote your partitioned VM?

**Comment by dompa** [comment]
Currently I'm just using your ChatRoomVM example with the addition of 
`public override string GroupName
   {
      get => _principalAccessor.Principal.Identity.Name;
   } 
`
from your Hackernoon article.

I was planning to get the GroupName from a Repository, but I went back to basics when it didn't work after I published it to Azure. Here is the code for the partitioned VM I'm using:

 ```
public class ChatMessage
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public DateTimeOffset Date { get; set; }
        public string Text { get; set; }
    }

```
    public class ChatUser
    {
        private static int _counter = 0;

        public string Id { get; set; }
        public string CorrelationId { get; set; }
        public string Name { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }


        public ChatUser(IConnectionContext connectionContext, string correlationId)
        {
            Id = connectionContext.ConnectionId;
            CorrelationId = correlationId;
            Name = $"user{Interlocked.Increment(ref _counter)}";
            IpAddress = connectionContext.HttpConnection.RemoteIpAddress.ToString();

            //var browserInfo = Parser.GetDefault().Parse(connectionContext.HttpRequestHeaders.UserAgent);
            //if (browserInfo != null)
            //    Browser = $"{browserInfo.UserAgent.Family}/{browserInfo.OS.Family} {browserInfo.OS.Major}";
        }
    }

    public class ChatRoomVM : MulticastVM
    {
        private readonly IConnectionContext _connectionContext;
        private readonly IPrincipalAccessor _principalAccessor;

        [ItemKey(nameof(ChatMessage.Id))]
        public List<ChatMessage> Messages { get; } = new List<ChatMessage>();

        [ItemKey(nameof(ChatUser.Id))]
        public List<ChatUser> Users { get; } = new List<ChatUser>();

        public bool Ready { get; set; }
        public Action<ChatMessage> SendMessage => chat =>
        {
            string userId = _connectionContext.ConnectionId;
            chat.Id = Messages.Count + 1;
            chat.UserId = userId;
            chat.UserName = UpdateUserName(userId, chat.UserName);

            var privateMessageUser = Users.FirstOrDefault(x => chat.Text.StartsWith($"{x.Name}:"));
            if (privateMessageUser != null)
                base.Send(new List<string> { privateMessageUser.Id, userId }, "PrivateMessage", chat);
            else
            {
                lock (Messages)
                {
                    Messages.Add(chat);
                    this.AddList(nameof(Messages), chat);
                }
            }
        };

        public Action<string> AddUser => correlationId =>
        {
            var user = new ChatUser(_connectionContext, correlationId);
            lock (Users)
            {
                Users.Add(user);
                this.AddList(nameof(Users), user);
            }
        };

        public Action RemoveUser => () =>
        {
            lock (Users)
            {
                var user = Users.FirstOrDefault(x => x.Id == _connectionContext.ConnectionId);
                if (user != null)
                {
                    Users.Remove(user);
                    this.RemoveList(nameof(Users), user.Id);
                }
            }
        };

        public ChatRoomVM(IConnectionContext connectionContext,IPrincipalAccessor principalAccessor)
        {
            _principalAccessor = principalAccessor;
            _connectionContext = connectionContext;
            Ready = true;
            Changed(nameof(Ready));
            PushUpdates();

        }
        public override string GroupName
        {
            get => _principalAccessor.Principal.Identity.Name;
        }
        public override void Dispose()
        {
            RemoveUser();
            PushUpdates();
            base.Dispose();
        }

        private string UpdateUserName(string userId, string userName)
        {
            lock (Users)
            {
                var user = Users.FirstOrDefault(x => x.Id == userId);
                if (user != null)
                {
                    if (!string.IsNullOrEmpty(userName))
                    {
                        user.Name = userName;
                        this.UpdateList(nameof(Users), user);
                    }
                    return user.Name;
                }
            }
            return userId;
        }
    }

**Comment by dompa** [comment]
Hi again,

I created a new project from scratch and just added AuthServer and the simple partitioned multicast VM and a razor chatpage.
This runs fine after publish to Azure web app, so I guess the problem is somewhere in my code.
Thanks for your help!

Regards,
Patrik
