### ISSUE TITLE
Broken web page - blazor.dotnetify.net/compositeview

### ISSUE THREAD

**Issue by ghhv** [dsuryd/dotNetify-Blazor#5]
Hi Dicky,
FYI this page is broken with a null exception - https://blazor.dotnetify.net/compositeview
Thanks for the everything you've done.

**Comment by ghhv** [comment]
I've been trying to implement a version of the composite view and seem to be getting stuck at the same point. Using mine and your sample code with the dev debug enabled, I now see this error. I can't figure out how this is meant to work - there's nothing obviously wrong to me. 
```
DotNetify: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww
            type=Request_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww
            type=Request_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM
            data={}
DotNetify: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww
            type=Response_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM
            data={"Apply":null,"Delete":null}
Website.Server.Startup: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww
            type=Response_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM
            data={"Apply":null,"Delete":null}
DotNetify: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww
            type=Request_VM
            vmId=null.MovieTableVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww
            type=Request_VM
            vmId=null.MovieTableVM
            data={}
DotNetify: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww Exception=[dotNetify] ERROR: 'null' is not a known view model! Its assembly must be registered through VMController.RegisterAssembly.
Website.Server.Startup: Information: [dotNetify] connId=PQmN3OXSqyy0--DOi4RUww Exception=[dotNetify] ERROR: 'null' is not a known view model! Its assembly must be registered through VMController.RegisterAssembly.
[CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM] received> 
[null.MovieTableVM] received> 
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Website.Client.Pages._2_Examples.CompositeView.MovieTable.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2) in C:\Data\git\dotNetify-Blazor-master\Website\Website.Client\Pages\2_Examples\CompositeView\MovieTable.razor:line 8
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DotNetify.Blazor.VMContext`1[[Website.Client.Pages._2_Examples.CompositeView.MovieTable.IMovieTableState, Website.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder __builder) in C:\Data\git\dotNetify-Blazor-master\Source\VMContext.razor:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Website.Client.Pages._2_Examples.CompositeView.MovieTable.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2) in C:\Data\git\dotNetify-Blazor-master\Website\Website.Client\Pages\2_Examples\CompositeView\MovieTable.razor:line 8
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DotNetify.Blazor.VMContext`1[[Website.Client.Pages._2_Examples.CompositeView.MovieTable.IMovieTableState, Website.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder __builder) in C:\Data\git\dotNetify-Blazor-master\Source\VMContext.razor:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by dsuryd** [comment]
There was a bug in one of the dependencies, the `dotnetify-elements' library.  It's fixed now and published.  The composite view example is working now.  Thank you for reporting the issue!

**Comment by ghhv** [comment]
Cheers, thanks!

**Comment by ghhv** [comment]
I can see your web site one is working now but even a fresh clone of this solution still has the same issue for me. I updated the SignalR package & then all other packages but alas, no working.. The other odd thing is I was not using Dotnetify Elements in my solution at all so not sure that is the answer.. 

```
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Dispose_VM
            vmId=Overview
            data=
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Request_VM
            vmId=CompositeViewDoc
            data={}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Response_VM
            vmId=CompositeViewDoc
            data={"Content":"<if view>\n##### CompositeView.razor\n\n```jsx\n@inject IStylesheet Stylesheet\n\n<VMContext VM=\"CompositeViewVM\" TState=\"object\">\n    <d-panel css=\"@Stylesheet[\"CompositeView\"]\" horizontal=\"true\">\n        <section>\n            <VMContext VM=\"FilterableMovieTableVM\" TState=\"object\">\n                <MovieTable />\n            </VMContext>\n        </section>\n        <aside>\n            <MovieDetails />\n            <MovieFilter />\n        </aside>\n    </d-panel>\n</VMContext>\n```\n\n##### MovieTable.razor\n\n```jsx\n<VMContext VM=\"MovieTableVM\" TState=\"IMovieTableState\" OnStateChange=\"UpdateState\">\n@if (state != null)\n{\n    <div>\n        <table>\n            <thead>\n                <tr>\n                    @foreach (var header in state.Headers)\n                    {\n                        <th @key=\"header\">@header</th>\n                    }\n                </tr>\n            </thead>\n            <tbody>\n                @foreach (var data in state.Data)\n                {\n                    <tr @key=\"data.Rank\"\n                        class=\"@(state.SelectedKey == data.Rank ? \"selected\" : \"\")\"\n                        @onclick=\"_ => state.SelectedKey = data.Rank\">\n                        <td>@data.Rank</td>\n                        <td>@data.Movie</td>\n                        <td>@data.Year</td>\n                        <td>@data.Director</td>\n                    </tr>\n                }\n            </tbody>\n        </table>\n        <div class=\"pagination\">\n            @foreach (var page in state.Pagination)\n            {\n                <div @key=\"page\"\n                     class=\"@(state.SelectedPage == page ? \"current\" : \"\")\"\n                     @onclick=\"_ => state.SelectedPage = page\">\n                    @(page)\n                </div>\n            }\n        </div>\n    </div>\n}\n</VMContext>\n\n@code {\n   private IMovieTableState state;\n\n   public interface IMovieTableState\n   {\n       string[] Headers { get; set; }\n       MovieRecord[] Data { get; set; }\n       int[] Pagination { get; set; }\n       [Watch] int SelectedKey { get; set; }\n       [Watch] int SelectedPage { get; set; }\n   }\n\n   public class MovieRecord\n   {\n       public int Rank { get; set; }\n       public string Movie { get; set; }\n       public int Year { get; set; }\n       public string Director { get; set; }\n       public string Cast { get; set; }\n   }\n\n   private void UpdateState(IMovieTableState state)\n   {\n       this.state = state;\n       StateHasChanged();\n   }\n}\n```\n\n##### MovieDetails.razor\n\n```jsx\n<VMContext VM=\"MovieDetailsVM\" TState=\"IMovieDetailsState\" OnStateChange=\"UpdateState\">\n@if (state != null)\n{\n    <div class=\"card\">\n        <header class=\"card-header\">\n            <b>@state.Movie.Movie</b>\n            <div>@state.Movie.Year</div>\n        </header>\n        <section class=\"card-body\">\n            <b>Director</b>\n            <p>@state.Movie.Director</p>\n            <b>Cast</b>\n            <div>\n                @foreach (var cast in state.Movie.Cast.Split(\",\"))\n                {\n                    <div>@cast</div>\n                }\n            </div>\n        </section>\n    </div>\n}\n</VMContext>\n\n@code {\n   private IMovieDetailsState state;\n\n   public interface IMovieDetailsState\n   {\n       MovieTable.MovieRecord Movie { get; set; }\n   }\n\n   private void UpdateState(IMovieDetailsState state)\n   {\n       this.state = state;\n       StateHasChanged();\n   }\n}\n```\n\n##### MovieFilter.razor\n\n```jsx\n<VMContext VM=\"FilterableMovieTableVM.MovieFilterVM\" TState=\"IMovieFilterState\" OnStateChange=\"UpdateState\">\n@if (state != null)\n{\n    <form>\n        <div class=\"filter card\">\n            <div class=\"card-header\">Filters</div>\n            <div class=\"card-body\">\n                <select class=\"form-control\"\n                        value=\"@filter\"\n                        @onchange=\"e => UpdateFilterDropdown(e.Value.ToString())\">\n                    @foreach (var text in movieProps)\n                    {\n                        <option value=\"@text\">@text</option>\n                    }\n                </select>\n                <div class=\"operation\">\n                    @foreach (var op in operations)\n                    {\n                        <div class=\"form-check\">\n                            <input class=\"form-check-input\"\n                                    type=\"radio\"\n                                    id=\"@op\"\n                                    value=\"@op\"\n                                    checked=\"@(operation == op)\"\n                                    @onchange=\"_ => operation = op\">\n                            <label class=\"form-check-label\" for=\"@op\">@op</label>\n                        </div>\n                    }\n                </div>\n                <input class=\"form-control\" @bind=\"text\" @bind:event=\"oninput\" >\n                <div>\n                    @foreach (var filter in filters)\n                    {\n                        <div class=\"chip\" @key=\"filter.Id\">\n                            @filter.Property @filter.Operation @filter.Text\n                            <div @onclick=\"_ => HandleDelete(filter.Id)\">\n                                <i class=\"material-icons\">clear</i>\n                            </div>\n                        </div>\n                    }\n                </div>\n            </div>\n            <div class=\"card-footer\">\n                <button class=\"btn btn-primary\" @onclick=\"HandleApply\" disabled=\"@string.IsNullOrWhiteSpace(text)\">Apply</button>\n            </div>\n        </div>\n    </form>\n}\n</VMContext>\n\n@code {\n   private IMovieFilterState state;\n   private List<Filter> filters = new List<Filter>();\n   private int filterId = 0;\n   private string filter = \"Any\";\n   private string[] movieProps = new string[] { \"Any\", \"Rank\", \"Movie\", \"Year\", \"Cast\", \"Director\" };\n   private string operation = \"contains\";\n   private string[] operations = new string[] { \"contains\" };\n   private string text = \"\";\n\n   public interface IMovieFilterState\n   {\n       void Apply(Filter filter);\n       void Delete(int filterId);\n   }\n\n   public class Filter\n   {\n       public int Id { get; set; }\n       public string Property { get; set; }\n       public string Operation { get; set; }\n       public string Text { get; set; }\n   }\n\n   private void HandleApply()\n   {\n       var newId = filterId + 1;\n       var newFilter = new Filter { Id = newId, Property = filter, Operation = operation, Text = text };\n\n       filterId = newId;\n       filters.Add(newFilter);\n       text = \"\";\n\n       state.Apply(newFilter);\n       UpdateFilterDropdown(\"Any\"); // Reset filter dropdown.\n   }\n\n   private void HandleDelete(int filterId)\n   {\n       state.Delete(filterId);\n       filters = filters.Where(filter => filter.Id != filterId).ToList();\n   }\n\n   private void UpdateFilterDropdown(string filter)\n   {\n       this.filter = filter;\n       if (filter == \"Rank\" || filter == \"Year\")\n       {\n           this.operations = new string[] { \"equals\", \">=\", \"<=\" };\n           this.operation = \"equals\";\n       }\n       else\n       {\n           this.operations = new string[] { \"contains\" };\n           this.operation = \"contains\";\n       }\n   }\n\n   private void UpdateState(IMovieFilterState state)\n   {\n       this.state = state;\n       StateHasChanged();\n   }\n}\n```\n\n</if>\n<if viewmodel>\n##### CompositeView.cs\n\n```csharp\npublic class CompositeViewVM : BaseVM\n{\n   private readonly IMovieService _movieService;\n\n   private event EventHandler<int> Selected;\n\n   public CompositeViewVM(IMovieService movieService)\n   {\n      _movieService = movieService;\n   }\n\n   public override void OnSubVMCreated(BaseVM subVM)\n   {\n      if (subVM is FilterableMovieTableVM)\n         InitMovieTableVM(subVM as FilterableMovieTableVM);\n      else if (subVM is MovieDetailsVM)\n         InitMovieDetailsVM(subVM as MovieDetailsVM);\n   }\n\n   private void InitMovieTableVM(FilterableMovieTableVM vm)\n   {\n      // Set the movie table data source to AFI Top 100 movies.\n      vm.DataSource = () => _movieService.GetAFITop100();\n\n      // When movie table selection changes, raise a private Selected event.\n      vm.Selected += (sender, rank) => Selected?.Invoke(this, rank);\n   }\n\n   private void InitMovieDetailsVM(MovieDetailsVM vm)\n   {\n      // Set default details to the highest ranked movie.\n      vm.SetByAFIRank(1);\n\n      // When the Selected event occurs, update the movie details.\n      Selected += (sender, rank) => vm.SetByAFIRank(rank);\n   }\n}\n```\n\n##### MovieTable.cs\n\n```csharp\npublic interface IPaginatedTable<T>\n{\n   IEnumerable<string> Headers { get; }\n   IEnumerable<T> Data { get; }\n   int SelectedKey { get; set; }\n   int[] Pagination { get; }\n   int SelectedPage { get; set; }\n}\n\npublic class MovieTableVM : BaseVM, IPaginatedTable<MovieRecord>\n{\n   private int _recordsPerPage = 10;\n   private Func<IEnumerable<MovieRecord>> _dataSourceFunc;\n\n   public IEnumerable<string> Headers => new string[] { \"Rank\", \"Movie\", \"Year\", \"Director\" };\n\n   public Func<IEnumerable<MovieRecord>> DataSource\n   {\n      set\n      {\n         _dataSourceFunc = value;\n         Changed(nameof(Data));\n      }\n   }\n\n   public IEnumerable<MovieRecord> Data => GetData();\n\n   public int SelectedKey\n   {\n      get => Get<int>();\n      set\n      {\n         Set(value);\n         Selected?.Invoke(this, value);\n      }\n   }\n\n   public int[] Pagination\n   {\n      get => Get<int[]>();\n      set\n      {\n         Set(value);\n         SelectedPage = 1;\n      }\n   }\n\n   public int SelectedPage\n   {\n      get => Get<int>();\n      set\n      {\n         Set(value);\n         Changed(nameof(Data));\n      }\n   }\n\n   public event EventHandler<int> Selected;\n\n   private IEnumerable<MovieRecord> GetData()\n   {\n      if (_dataSourceFunc == null)\n         return null;\n\n      var data = _dataSourceFunc();\n      if (!data.Any(i => i.Rank == SelectedKey))\n         SelectedKey = data.Count() > 0 ? data.First().Rank : -1;\n\n      return Paginate(data);\n   }\n\n   private IEnumerable<MovieRecord> Paginate(IEnumerable<MovieRecord> data)\n   {\n      // ChangedProperties is a base class property that contains a list of changed properties.\n      // Here it's used to check whether user has changed the SelectedPage property value by clicking a pagination button.\n      if (this.HasChanged(nameof(SelectedPage)))\n         return data.Skip(_recordsPerPage * (SelectedPage - 1)).Take(_recordsPerPage);\n      else\n      {\n         var pageCount = (int)Math.Ceiling(data.Count() / (double)_recordsPerPage);\n         Pagination = Enumerable.Range(1, pageCount).ToArray();\n         return data.Take(_recordsPerPage);\n      }\n   }\n}\n```\n\n##### FilterableMovieTable.cs\n\n```csharp\npublic class FilterableMovieTableVM : BaseVM\n{\n   private Func<IEnumerable<MovieRecord>> _dataSourceFunc;\n   private Action _updateData;\n   private string _query;\n\n   public event EventHandler<int> Selected;\n\n   public Func<IEnumerable<MovieRecord>> DataSource\n   {\n      set\n      {\n         _dataSourceFunc = value;\n         _updateData?.Invoke();\n      }\n   }\n\n   // This method is called when an instance of a view model inside this view model's scope is being created.\n   // It provides a chance for this view model to initialize them.\n   public override void OnSubVMCreated(BaseVM subVM)\n   {\n      if (subVM is MovieTableVM)\n         InitMovieTableVM(subVM as MovieTableVM);\n      else if (subVM is MovieFilterVM)\n         InitMovieFilterVM(subVM as MovieFilterVM);\n   }\n\n   private void InitMovieTableVM(MovieTableVM vm)\n   {\n      // Forward the movie table's Selected event.\n      vm.Selected += (sender, key) => Selected?.Invoke(this, key);\n\n      // Create an action to update the movie table with the filtered data.\n      _updateData = () => vm.DataSource = GetFilteredData;\n      _updateData();\n   }\n\n   private void InitMovieFilterVM(MovieFilterVM vm)\n   {\n      // If a filter is added, set the filter query and update the movie table data.\n      vm.FilterChanged += (sender, query) =>\n      {\n         _query = query;\n         _updateData?.Invoke();\n      };\n   }\n\n   private IEnumerable<MovieRecord> GetFilteredData()\n   {\n      try\n      {\n         return !string.IsNullOrEmpty(_query) ?\n         _dataSourceFunc().AsQueryable().Where(_query) : _dataSourceFunc();\n      }\n      catch (Exception)\n      {\n         return new List<MovieRecord>();\n      }\n   }\n}\n```\n\n##### MovieDetails.cs\n\n```csharp\npublic class MovieDetailsVM : BaseVM\n{\n   private readonly IMovieService _movieService;\n\n   public MovieRecord Movie\n   {\n      get { return Get<MovieRecord>(); }\n      set { Set(value); }\n   }\n\n   public MovieDetailsVM(IMovieService movieService)\n   {\n      _movieService = movieService;\n   }\n\n   public void SetByAFIRank(int rank) => Movie = _movieService.GetMovieByAFIRank(rank);\n}\n```\n\n##### MovieFilter.cs\n\n```csharp\npublic class MovieFilterVM : BaseVM\n{\n   private List<MovieFilter> _filters = new List<MovieFilter>();\n\n   public class MovieFilter\n   {\n      public int Id { get; set; }\n      public string Property { get; set; }\n      public string Operation { get; set; }\n      public string Text { get; set; }\n\n      public string ToQuery()\n      {\n         if (Operation == \"contains\")\n            return Property == \"Any\" ? $\"( Movie + Cast + Director ).toLower().contains(\\\"{Text.ToLower()}\\\")\"\n               : $\"{Property}.toLower().contains(\\\"{Text.ToLower()}\\\")\";\n         else\n         {\n            int intValue = int.Parse(Text);\n            if (Operation == \"equals\")\n               return $\"{Property} == {intValue}\";\n            else\n               return $\"{Property} {Operation} {intValue}\";\n         }\n      }\n\n      public static string BuildQuery(IEnumerable<MovieFilter> filters) => string.Join(\" and \", filters.Select(i => i.ToQuery()));\n   }\n\n   public Action<MovieFilter> Apply => arg =>\n   {\n      _filters.Add(arg);\n      FilterChanged?.Invoke(this, MovieFilter.BuildQuery(_filters));\n   };\n\n   public Action<int> Delete => id =>\n   {\n      _filters = _filters.Where(i => i.Id != id).ToList();\n      FilterChanged?.Invoke(this, MovieFilter.BuildQuery(_filters));\n   };\n\n   public event EventHandler<string> FilterChanged;\n}\n```\n\n</if>\n"}
[CompositeViewDoc] received> 
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Dispose_VM
            vmId=CompositeViewDoc.CompositeViewVM
            data=
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Request_VM
            vmId=CompositeViewDoc.CompositeViewVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Response_VM
            vmId=CompositeViewDoc.CompositeViewVM
            data={}
[CompositeViewDoc.CompositeViewVM] received> 
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Request_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Response_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Request_VM
            vmId=CompositeViewDoc.CompositeViewVM.MovieDetailsVM
            data={}
[CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM] received> 
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Response_VM
            vmId=CompositeViewDoc.CompositeViewVM.MovieDetailsVM
            data={"Movie":{"Rank":1,"Movie":"Citizen Kane","Year":1941,"Cast":"Orson Welles, Joseph Cotten, Dorothy Comingore","Director":"Orson Welles"}}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Request_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Response_VM
            vmId=CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM
            data={"Apply":null,"Delete":null}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA
            type=Request_VM
            vmId=null.MovieTableVM
            data={}
Website.Server.Startup: Information: [dotNetify] connId=eYTwMGXo6sFP9rXEZCEHtA Exception=[dotNetify] ERROR: 'null' is not a known view model! Its assembly must be registered through VMController.RegisterAssembly.
[CompositeViewDoc.CompositeViewVM.MovieDetailsVM] received> 
[CompositeViewDoc.CompositeViewVM.FilterableMovieTableVM.MovieFilterVM] received> 
[null.MovieTableVM] received> 
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Website.Client.Pages._2_Examples.CompositeView.MovieTable.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2) in C:\Data\git\dotNetify-Blazor-master-v2\dotNetify-Blazor-master\Website\Website.Client\Pages\2_Examples\CompositeView\MovieTable.razor:line 8
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DotNetify.Blazor.VMContext`1[[Website.Client.Pages._2_Examples.CompositeView.MovieTable.IMovieTableState, Website.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder __builder) in C:\Data\git\dotNetify-Blazor-master-v2\dotNetify-Blazor-master\Source\VMContext.razor:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Website.Client.Pages._2_Examples.CompositeView.MovieTable.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2) in C:\Data\git\dotNetify-Blazor-master-v2\dotNetify-Blazor-master\Website\Website.Client\Pages\2_Examples\CompositeView\MovieTable.razor:line 8
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at DotNetify.Blazor.VMContext`1[[Website.Client.Pages._2_Examples.CompositeView.MovieTable.IMovieTableState, Website.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder __builder) in C:\Data\git\dotNetify-Blazor-master-v2\dotNetify-Blazor-master\Source\VMContext.razor:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by dsuryd** [comment]
Sorry, I apparently hadn't pushed my local revision.  Please try again.   Your `index.html` should have a link to `dotnetify-elements.bundle.js`.  The fix is in the recently published version of that file,

**Comment by ghhv** [comment]
yes, sorry, I do have this - https://unpkg.com/dotnetify-elements@latest/lib/dotnetify-elements.bundle.js - nothing server side though. 

And yes, the fresh clone is working now. Thanks!
